#!/usr/bin/env sh

## Define missing scancode-to-keycode mappings for the Alienware 17r5 laptop.
##
## NOTE: scancodes can be found in the output of ``dmesg --follow'' when
##       unmapped keys are pressed.


## Enable debugging output
if [[ -n ${DEBUG} ]]; then
  set -"${DEBUGOPTS:-xv}"
fi


## If called by non-root user, exit.
if test "$(id -u)" -ne 0; then
  printf '%s: Permission denied\n' "${0##*/}" 1>&2
  exit 1
fi


## LHS Macros
setkeycodes e011 135  # MacroX MENU
setkeycodes e012 192  # Macro1
setkeycodes e013 193  # Macro2
setkeycodes e014 194  # Macro3
setkeycodes e015 195  # Macro4
setkeycodes e016 196  # Macro5

## RHS Macros
setkeycodes e017 197  # Macro6
setkeycodes e018 198  # Macro7
setkeycodes e01a 199  # Macro8
setkeycodes e01b 200  # Macro9

## Multimedia keys (Fn)
setkeycodes e040      # F1   Alienware Graphics Amplifier
setkeycodes e004 238  # F2   WLAN
setkeycodes e000 238  # F6   Fn lock switched to function keys
setkeycodes e001 238  # F6   Fn lock switched to multimedia keys
setkeycodes e03a 173  # F8   REFRESH
setkeycodes e005 224  # F9   BRIGHTNESSDOWN
setkeycodes e006 225  # F10  BRIGHTNESSUP
setkeycodes 69   228  # F12  KBDILLUMTOGGLE


## Done
exit 0
