#!/usr/bin/env sh
#
# home-user-bind-generator
#
# > Generates mount units upon boot, defining bind mounts from the contents
#   of a user directory below /users into the equivalent location in /home.
#
# > Since /users and /home may not be mounted when this script runs,
#   the directories considered will be those found in /etc/skel.
#
#
# - TODO:
# * Abstract to dynamically configurable users using a template generator


set -u

if ! exec 2>/dev/null; then
  exit 1
fi

if ! unset path prefix target unit user; then
  exit 1
fi

user='pat'

target="$1/multi-user.target.wants"

prefix="$1/home-${user}"


mkdir -p "${target}" || exit 1


for path in /etc/skel/* /etc/skel/.* ; do
  case "${path##*/}" in
    .|..) continue ;;
  esac

  if ! test -d "${path}"; then
    continue
  fi

  if test -L "${path}"; then
    continue
  fi

  path="${path##*/}"

  unit="${prefix}-${path}.mount"


  ln -sf "${unit}" "${target}"

  cat << }}} >| "${unit}"
[Unit]
RequiresMountsFor=/home
RequiresMountsFor=/users
ConditionPathIsDirectory=/home/${user}
ConditionPathIsDirectory=/users/${user}/${path}

[Mount]
What=/users/${user}/${path}
Where=/home/${user}/${path}
Options=rbind,nofail
Type=none

[Install]
WantedBy=multi-user.target
}}}

done

exit 0
