#!/usr/bin/env bash

test "$#" -eq 1 || {
  printf 'usage: %q DESTINATION\n' "${0##*/}" 1>&2
  exit 2
}

set -- "$(realpath "$1"; printf +)"
set -- "${1%??}"

mkdir -p "$1" || {
  printf 'error: %q: failed to create directory\n' "$1" 1>&2
  exit 1
}

test -r "$1" && test -w "$1" && test -x "$1" || {
  printf 'error: %q: insufficient priviledges\n' "$1" 1>&2
  exit 1
}

trap '
echo
while true; do
  read -r -p '"'"'Do you really want to exit? (y/n): '"'"' &&
    case "${REPLY,,}" in
      y*)
        printf '"'"'Exiting...\n'"'"'
        kill -s INT $$
        ;;
      n*)
        printf '"'"'Press ENTER to resume...\n'"'"'
        break
        ;;
      *)
        continue
        ;;
    esac
  echo
done
' SIGINT


printf 'Destination set to %q\n' "$1"


while read -r -p 'Target URL: ' || true; do
  if test -n "${REPLY}"; then
    youtube-dl              \
      --ignore-errors       \
      --no-cache-dir        \
      --restrict-filenames  \
      --output "$1/%(title)s-%(id)s.%(ext)s" "${REPLY}" 1>/dev/null 2>&1 &
  fi
done


# vi:ft=sh:tw=78
